server.protocol=http
server.hostname=localhost
server.port=8080

fs.download_directory=/tmp/yt-dlp-web
fs.log_directory=/opt/yt-dlp-web/logs
fs.js_runtime_type=node
fs.js_runtime_path=/usr/bin/node

auth.users_file=./users.conf
