package net.firzen.web.network

import io.ktor.server.sessions.SessionSerializer
import io.ktor.server.sessions.SessionStorage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import net.firzen.web.UserManager
import java.io.File
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.StandardCopyOption.ATOMIC_MOVE
import java.nio.file.StandardCopyOption.REPLACE_EXISTING
import java.time.Instant
import java.util.UUID

private const val SESSION_FILE_SUFFIX = ".sessions"
private const val RECORD_SEPARATOR = '\t'
private const val UNKNOWN_CLIENT_ADDRESS = "unknown"
private val SESSION_ID_PATTERN = Regex("^[A-Za-z0-9_-]+$")
private val SESSION_JSON = Json { ignoreUnknownKeys = true }

/**
 * Serializes the server-side session fields passed through Ktor's storage API.
 */
internal object UserSessionSerializer : SessionSerializer<UserSession> {
    /**
     * Serializes the authenticated username and login address.
     *
     * @param session user session to serialize
     * @return serialized session fields
     */
    override fun serialize(session: UserSession): String {
        requireValidUserSession(session)

        return SESSION_JSON.encodeToString(session)
    }

    /**
     * Restores and validates a user session from its stored fields.
     *
     * @param text serialized session fields
     * @return restored user session
     * @throws IllegalArgumentException when a stored field is invalid
     * @throws kotlinx.serialization.SerializationException when [text] is malformed
     */
    override fun deserialize(text: String): UserSession {
        val session = SESSION_JSON.decodeFromString<UserSession>(text)
        requireValidUserSession(session)

        return session
    }
}

/**
 * Validates fields that are persisted in a user session record.
 *
 * @param session session whose username and client address should be validated
 * @throws IllegalArgumentException when a session field is invalid
 */
private fun requireValidUserSession(session: UserSession) {
    require(UserManager.isValidUsername(session.username)) { "Invalid session username" }
    require(session.clientAddress.isNotBlank()) { "Invalid session client address" }
    require(session.clientAddress.none { it == '\t' || it == '\r' || it == '\n' }) {
        "Invalid session client address"
    }
    require(isValidOperatingSystem(session.operatingSystem)) { "Invalid session operating system" }
}

/**
 * Stores opaque session identifiers in one plaintext file per authenticated user.
 *
 * @param directory directory containing user session files
 * @param lifetimeSeconds maximum server-side session lifetime in seconds
 * @param currentEpochSeconds clock used to calculate and verify expiration
 * @throws IllegalArgumentException when [lifetimeSeconds] is not positive
 * @throws IllegalStateException when [directory] cannot be created or used
 */
internal class UserFileSessionStorage(
    private val directory: File,
    private val lifetimeSeconds: Long,
    private val currentEpochSeconds: () -> Long = { Instant.now().epochSecond }
) : SessionStorage {
    private val lock = Any()
    private val sessions = mutableMapOf<String, StoredSession>()

    init {
        require(lifetimeSeconds > 0) { "Session lifetime must be positive" }
        prepareDirectory()
        loadSessions()
    }

    /**
     * Returns current sessions for all users or one requested user.
     *
     * @param username optional username used to filter sessions
     * @return active sessions sorted by username, creation time, and identifier
     * @throws IllegalArgumentException when [username] is invalid
     * @throws java.io.IOException when session files cannot be read or normalized
     */
    fun activeSessions(username: String? = null): List<ActiveSession> {
        if (username != null) {
            require(UserManager.isValidUsername(username)) { "Invalid session username" }
        }

        return synchronized(lock) {
            sessions.clear()
            loadSessions()

            sessions.mapNotNull { (id, session) ->
                session.toActiveSession(id, lifetimeSeconds)
                    .takeIf { username == null || it.username == username }
            }.sortedWith(compareBy(ActiveSession::username, ActiveSession::createdAt, ActiveSession::id))
        }
    }

    /**
     * Stores or replaces an opaque session identifier for a username.
     *
     * @param id opaque identifier generated by Ktor
     * @param value serialized user session
     * @throws IllegalArgumentException when [id] or [value] is invalid
     * @throws java.io.IOException when session data cannot be persisted
     */
    override suspend fun write(id: String, value: String) = withContext(Dispatchers.IO) {
        val userSession = UserSessionSerializer.deserialize(value)
        requireValidSessionId(id)

        synchronized(lock) {
            val username = userSession.username
            val previousUser = sessions[id]?.username
            reloadUser(username)
            if (previousUser != null && previousUser != username) reloadUser(previousUser)

            sessions[id] = StoredSession(
                username, currentEpochSeconds(), userSession.clientAddress, userSession.operatingSystem
            )

            if (previousUser != null && previousUser != username) persistUser(previousUser)
            persistUser(username)
        }
    }

    /**
     * Resolves an unexpired session identifier to its serialized username.
     *
     * @param id opaque session identifier supplied by the browser
     * @return serialized username associated with [id]
     * @throws NoSuchElementException when the session is unknown or expired
     * @throws java.io.IOException when expired session data cannot be persisted
     */
    override suspend fun read(id: String): String = withContext(Dispatchers.IO) {
        synchronized(lock) {
            val session = sessions[id] ?: throw missingSession(id)

            if (!isPersisted(id, session)) {
                reloadAndNormalizeUser(session.username)
                throw missingSession(id)
            }

            if (expirationTime(session.createdAt) <= currentEpochSeconds()) {
                reloadAndNormalizeUser(session.username)
                throw missingSession(id)
            }

            UserSessionSerializer.serialize(
                UserSession(session.username, session.clientAddress, session.operatingSystem)
            )
        }
    }

    /**
     * Removes a session identifier from memory and its user's session file.
     *
     * @param id opaque session identifier to invalidate
     * @throws java.io.IOException when updated session data cannot be persisted
     */
    override suspend fun invalidate(id: String) = withContext(Dispatchers.IO) {
        synchronized(lock) {
            val username = sessions[id]?.username ?: return@synchronized
            reloadUser(username)

            val session = sessions.remove(id) ?: return@synchronized
            persistUser(session.username)
        }
    }

    /**
     * Reports whether a cached session still exists unchanged in its backing file.
     *
     * @param id opaque session identifier to verify
     * @param session cached session record to compare
     * @return `true` when the exact record remains persisted
     * @throws java.io.IOException when the session file cannot be read
     */
    private fun isPersisted(id: String, session: StoredSession): Boolean {
        val expectedLine = sessionRecordLine(id, session)
        val file = sessionFile(session.username)

        return file.exists() && file.useLines { lines ->
            lines.any { it == expectedLine }
        }
    }

    /**
     * Reloads one user's cached sessions from its authoritative file.
     *
     * @param username user whose cached records should be refreshed
     * @throws java.io.IOException when the session file cannot be read
     */
    private fun reloadUser(username: String) {
        sessions.entries.removeIf { it.value.username == username }

        val file = sessionFile(username)
        if (file.exists()) loadUserFile(file)
    }

    /**
     * Reloads a user file and removes its malformed or expired records.
     *
     * @param username user whose session file should be normalized
     * @throws java.io.IOException when session data cannot be read or persisted
     */
    private fun reloadAndNormalizeUser(username: String) {
        reloadUser(username)
        persistUser(username)
    }

    /**
     * Creates and validates the configured session directory.
     *
     * @throws IllegalStateException when the directory cannot be created or used
     */
    private fun prepareDirectory() {
        check(directory.exists() || directory.mkdirs()) {
            "Could not create session directory: ${directory.absolutePath}"
        }
        check(directory.isDirectory && directory.canRead() && directory.canWrite()) {
            "Session path is not a readable and writable directory: ${directory.absolutePath}"
        }
    }

    /**
     * Loads valid, unexpired records and normalizes every recognized user file.
     *
     * @throws java.io.IOException when existing session data cannot be read or rewritten
     */
    private fun loadSessions() {
        val files = directory.listFiles()
            ?.filter { it.isFile && it.name.endsWith(SESSION_FILE_SUFFIX) }
            .orEmpty()
        val usernames = files.mapNotNull(::loadUserFile).toSet()

        usernames.forEach(::persistUser)
    }

    /**
     * Loads valid records from one user's session file.
     *
     * @param file session file to read
     * @return valid username represented by the file, or `null` for an invalid filename
     * @throws java.io.IOException when [file] cannot be read
     */
    private fun loadUserFile(file: File): String? {
        val username = file.name.removeSuffix(SESSION_FILE_SUFFIX)
        if (!UserManager.isValidUsername(username)) return null

        val lines = file.readLines()
        val storesCreationTime = !usesLegacyExpirationTimestamps(file, lines)

        lines.asSequence().filterNot { it.startsWith('#') }.forEach { line ->
            parseRecord(username, line, storesCreationTime)?.let { (id, session) ->
                sessions[id] = session
            }
        }

        return username
    }

    /**
     * Detects the previous format whose timestamps represented expiration times.
     *
     * @param file session file whose modification time is used for comparison
     * @param lines plaintext records loaded from [file]
     * @return `true` when a record timestamp is later than the file creation-era write time
     */
    private fun usesLegacyExpirationTimestamps(file: File, lines: List<String>): Boolean {
        if (lines.firstOrNull()?.startsWith('#') == true) return false

        val fileTimestamp = file.lastModified() / 1000

        return lines.asSequence()
            .mapNotNull { line ->
                line.split(RECORD_SEPARATOR, limit = 3).getOrNull(1)?.toLongOrNull()
            }
            .any { it > currentEpochSeconds() || it > fileTimestamp + 1 }
    }

    /**
     * Parses one unexpired session record.
     *
     * @param username username represented by the containing file
     * @param line tab-separated identifier, timestamp, client address, and operating system
     * @param storesCreationTime whether the file uses the current creation-time format
     * @return parsed identifier and session, or `null` for malformed or expired data
     */
    private fun parseRecord(
        username: String,
        line: String,
        storesCreationTime: Boolean
    ): Pair<String, StoredSession>? {
        val fields = line.split(RECORD_SEPARATOR, limit = 4)
        if (fields.size !in 2..4 || !SESSION_ID_PATTERN.matches(fields[0])) return null

        val storedTimestamp = fields[1].toLongOrNull() ?: return null
        val createdAt = resolveCreationTime(storedTimestamp, storesCreationTime) ?: return null
        if (expirationTime(createdAt) <= currentEpochSeconds()) return null
        val clientAddress = fields.getOrElse(2) { UNKNOWN_CLIENT_ADDRESS }
        if (!isValidClientAddress(clientAddress)) return null
        val operatingSystem = fields.getOrElse(3) { "unknown" }
        if (!isValidOperatingSystem(operatingSystem)) return null

        return fields[0] to StoredSession(username, createdAt, clientAddress, operatingSystem)
    }

    /**
     * Reads a creation timestamp directly or derives it from a legacy expiration value.
     *
     * @param storedTimestamp timestamp found in a session record
     * @param storesCreationTime whether the timestamp already represents creation
     * @return session creation time, or `null` when a legacy session already expired
     * @throws ArithmeticException when a legacy timestamp cannot be converted
     */
    private fun resolveCreationTime(
        storedTimestamp: Long,
        storesCreationTime: Boolean
    ): Long? {
        if (storesCreationTime) return storedTimestamp
        if (storedTimestamp <= currentEpochSeconds()) return null

        return Math.subtractExact(storedTimestamp, lifetimeSeconds)
    }

    /**
     * Rewrites or removes one user's session file to match current in-memory state.
     *
     * @param username user whose active sessions should be persisted
     * @throws java.io.IOException when session data cannot be written or moved
     */
    private fun persistUser(username: String) {
        val records = sessions.entries
            .filter { it.value.username == username }
            .sortedBy { it.key }
        val destination = sessionFile(username)

        if (records.isEmpty()) {
            Files.deleteIfExists(destination.toPath())
            return
        }

        val content = records.joinToString("\n", postfix = "\n") {
            sessionRecordLine(it.key, it.value)
        }

        replaceFile(destination, content)
    }

    /**
     * Formats one session as a plaintext file record.
     *
     * @param id opaque session identifier
     * @param session stored session fields
     * @return tab-separated session record
     */
    private fun sessionRecordLine(id: String, session: StoredSession): String {
        return "$id$RECORD_SEPARATOR${session.createdAt}" +
            "$RECORD_SEPARATOR${session.clientAddress}$RECORD_SEPARATOR${session.operatingSystem}"
    }

    /**
     * Atomically replaces a session file when the filesystem supports it.
     *
     * @param destination final session file
     * @param content complete plaintext file contents
     * @throws java.io.IOException when the temporary or destination file cannot be written
     */
    private fun replaceFile(destination: File, content: String) {
        val temporary = File(directory, ".${destination.name}.${UUID.randomUUID()}.tmp")
        temporary.writeText(content)
        restrictPermissions(temporary)

        try {
            Files.move(temporary.toPath(), destination.toPath(), REPLACE_EXISTING, ATOMIC_MOVE)
        } catch (_: AtomicMoveNotSupportedException) {
            Files.move(temporary.toPath(), destination.toPath(), REPLACE_EXISTING)
        }

        restrictPermissions(destination)
    }

    /**
     * Limits a session file to owner read and write access where supported.
     *
     * @param file session file whose permissions should be restricted
     */
    private fun restrictPermissions(file: File) {
        file.setReadable(false, false)
        file.setWritable(false, false)
        file.setExecutable(false, false)
        file.setReadable(true, true)
        file.setWritable(true, true)
    }

    /**
     * Validates an identifier before persisting a session.
     *
     * @param id opaque session identifier generated by Ktor
     * @throws IllegalArgumentException when [id] is invalid
     */
    private fun requireValidSessionId(id: String) {
        require(SESSION_ID_PATTERN.matches(id)) { "Invalid session identifier" }
    }

    /**
     * Calculates expiration from a stored creation timestamp and current configured lifetime.
     *
     * @param createdAt session creation time as Unix epoch seconds
     * @return expiration time as Unix epoch seconds
     * @throws ArithmeticException when the configured lifetime overflows a timestamp
     */
    private fun expirationTime(createdAt: Long): Long {
        return Math.addExact(createdAt, lifetimeSeconds)
    }

    /**
     * Creates the file path assigned to a validated username.
     *
     * @param username username represented by the session file
     * @return session file inside the configured directory
     */
    private fun sessionFile(username: String): File {
        return File(directory, "$username$SESSION_FILE_SUFFIX")
    }

    /**
     * Creates Ktor's expected exception for an unavailable session identifier.
     *
     * @param id unavailable session identifier
     * @return missing-session exception
     */
    private fun missingSession(id: String): NoSuchElementException {
        return NoSuchElementException("Session not found: $id")
    }
}

/**
 * Associates an authenticated username with a server-side creation timestamp.
 *
 * @param username authenticated account name
 * @param createdAt creation time as Unix epoch seconds
 * @param clientAddress network address used to create the session
 * @param operatingSystem operating system reported at login
 */
private data class StoredSession(
    val username: String,
    val createdAt: Long,
    val clientAddress: String,
    val operatingSystem: String
)

/**
 * Converts a stored record into a read-only CLI session summary.
 *
 * @receiver stored session record to summarize
 * @param id opaque session identifier associated with this record
 * @param lifetimeSeconds current configured session lifetime
 * @return active session summary
 * @throws ArithmeticException when the configured lifetime overflows a timestamp
 */
private fun StoredSession.toActiveSession(id: String, lifetimeSeconds: Long): ActiveSession {
    return ActiveSession(
        id,
        username,
        createdAt,
        Math.addExact(createdAt, lifetimeSeconds),
        clientAddress,
        operatingSystem
    )
}

/**
 * Describes one active session for administrative CLI output.
 *
 * @param id opaque session identifier
 * @param username authenticated account name
 * @param createdAt creation time as Unix epoch seconds
 * @param expiresAt expiration time as Unix epoch seconds
 * @param clientAddress network address used to create the session
 * @param operatingSystem operating system reported at login
 */
internal data class ActiveSession(
    val id: String,
    val username: String,
    val createdAt: Long,
    val expiresAt: Long,
    val clientAddress: String,
    val operatingSystem: String
)

/**
 * Checks that an operating system name is safe to store and print in the terminal.
 *
 * @param operatingSystem reported operating system name
 * @return `true` for a nonblank value without control characters
 */
private fun isValidOperatingSystem(operatingSystem: String): Boolean {
    return operatingSystem.isNotBlank() && operatingSystem.none { it.isISOControl() }
}

/**
 * Reports whether a client address can be represented by one plaintext record field.
 *
 * @param clientAddress network address to validate
 * @return `true` when the address is nonblank and contains no record separators
 */
private fun isValidClientAddress(clientAddress: String): Boolean {
    return clientAddress.isNotBlank() &&
        clientAddress.none { it == '\t' || it == '\r' || it == '\n' }
}
