package net.firzen.web.network

import io.ktor.server.sessions.SessionSerializer
import io.ktor.server.sessions.SessionStorage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import net.firzen.web.UserManager
import java.io.File
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.StandardCopyOption.ATOMIC_MOVE
import java.nio.file.StandardCopyOption.REPLACE_EXISTING
import java.time.Instant
import java.util.UUID

private const val SESSION_FILE_SUFFIX = ".sessions"
private const val RECORD_SEPARATOR = '\t'
private val SESSION_ID_PATTERN = Regex("^[A-Za-z0-9_-]+$")

/**
 * Serializes a user session as its username for server-side storage.
 */
internal object UserSessionSerializer : SessionSerializer<UserSession> {
    /**
     * Returns the authenticated username stored by the session backend.
     *
     * @param session user session to serialize
     * @return authenticated username
     */
    override fun serialize(session: UserSession): String = session.username

    /**
     * Restores a user session from a validated stored username.
     *
     * @param text stored username
     * @return restored user session
     * @throws IllegalArgumentException when the stored username is invalid
     */
    override fun deserialize(text: String): UserSession {
        require(UserManager.isValidUsername(text)) { "Invalid session username" }

        return UserSession(text)
    }
}

/**
 * Stores opaque session identifiers in one plaintext file per authenticated user.
 *
 * @param directory directory containing user session files
 * @param lifetimeSeconds maximum server-side session lifetime in seconds
 * @param currentEpochSeconds clock used to calculate and verify expiration
 * @throws IllegalArgumentException when [lifetimeSeconds] is not positive
 * @throws IllegalStateException when [directory] cannot be created or used
 */
internal class UserFileSessionStorage(
    private val directory: File,
    private val lifetimeSeconds: Long,
    private val currentEpochSeconds: () -> Long = { Instant.now().epochSecond }
) : SessionStorage {
    private val lock = Any()
    private val sessions = mutableMapOf<String, StoredSession>()

    init {
        require(lifetimeSeconds > 0) { "Session lifetime must be positive" }
        prepareDirectory()
        loadSessions()
    }

    /**
     * Stores or replaces an opaque session identifier for a username.
     *
     * @param id opaque identifier generated by Ktor
     * @param value serialized username
     * @throws IllegalArgumentException when [id] or [value] is invalid
     * @throws java.io.IOException when session data cannot be persisted
     */
    override suspend fun write(id: String, value: String) = withContext(Dispatchers.IO) {
        requireValidSession(id, value)

        synchronized(lock) {
            val previousUser = sessions[id]?.username
            reloadUser(value)
            if (previousUser != null && previousUser != value) reloadUser(previousUser)

            sessions[id] = StoredSession(value, expirationTime())

            if (previousUser != null && previousUser != value) persistUser(previousUser)
            persistUser(value)
        }
    }

    /**
     * Resolves an unexpired session identifier to its serialized username.
     *
     * @param id opaque session identifier supplied by the browser
     * @return serialized username associated with [id]
     * @throws NoSuchElementException when the session is unknown or expired
     * @throws java.io.IOException when expired session data cannot be persisted
     */
    override suspend fun read(id: String): String = withContext(Dispatchers.IO) {
        synchronized(lock) {
            val session = sessions[id] ?: throw missingSession(id)

            if (!isPersisted(id, session)) {
                reloadAndNormalizeUser(session.username)
                throw missingSession(id)
            }

            if (session.expiresAt <= currentEpochSeconds()) {
                reloadAndNormalizeUser(session.username)
                throw missingSession(id)
            }

            session.username
        }
    }

    /**
     * Removes a session identifier from memory and its user's session file.
     *
     * @param id opaque session identifier to invalidate
     * @throws java.io.IOException when updated session data cannot be persisted
     */
    override suspend fun invalidate(id: String) = withContext(Dispatchers.IO) {
        synchronized(lock) {
            val username = sessions[id]?.username ?: return@synchronized
            reloadUser(username)

            val session = sessions.remove(id) ?: return@synchronized
            persistUser(session.username)
        }
    }

    /**
     * Reports whether a cached session still exists unchanged in its backing file.
     *
     * @param id opaque session identifier to verify
     * @param session cached session record to compare
     * @return `true` when the exact record remains persisted
     * @throws java.io.IOException when the session file cannot be read
     */
    private fun isPersisted(id: String, session: StoredSession): Boolean {
        val expectedLine = "$id$RECORD_SEPARATOR${session.expiresAt}"
        val file = sessionFile(session.username)

        return file.exists() && file.useLines { lines ->
            lines.any { it == expectedLine }
        }
    }

    /**
     * Reloads one user's cached sessions from its authoritative file.
     *
     * @param username user whose cached records should be refreshed
     * @throws java.io.IOException when the session file cannot be read
     */
    private fun reloadUser(username: String) {
        sessions.entries.removeIf { it.value.username == username }

        val file = sessionFile(username)
        if (file.exists()) loadUserFile(file)
    }

    /**
     * Reloads a user file and removes its malformed or expired records.
     *
     * @param username user whose session file should be normalized
     * @throws java.io.IOException when session data cannot be read or persisted
     */
    private fun reloadAndNormalizeUser(username: String) {
        reloadUser(username)
        persistUser(username)
    }

    /**
     * Creates and validates the configured session directory.
     *
     * @throws IllegalStateException when the directory cannot be created or used
     */
    private fun prepareDirectory() {
        check(directory.exists() || directory.mkdirs()) {
            "Could not create session directory: ${directory.absolutePath}"
        }
        check(directory.isDirectory && directory.canRead() && directory.canWrite()) {
            "Session path is not a readable and writable directory: ${directory.absolutePath}"
        }
    }

    /**
     * Loads valid, unexpired records and normalizes every recognized user file.
     *
     * @throws java.io.IOException when existing session data cannot be read or rewritten
     */
    private fun loadSessions() {
        val files = directory.listFiles()
            ?.filter { it.isFile && it.name.endsWith(SESSION_FILE_SUFFIX) }
            .orEmpty()
        val usernames = files.mapNotNull(::loadUserFile).toSet()

        usernames.forEach(::persistUser)
    }

    /**
     * Loads valid records from one user's session file.
     *
     * @param file session file to read
     * @return valid username represented by the file, or `null` for an invalid filename
     * @throws java.io.IOException when [file] cannot be read
     */
    private fun loadUserFile(file: File): String? {
        val username = file.name.removeSuffix(SESSION_FILE_SUFFIX)
        if (!UserManager.isValidUsername(username)) return null

        file.forEachLine { line ->
            parseRecord(username, line)?.let { (id, session) ->
                sessions[id] = session
            }
        }

        return username
    }

    /**
     * Parses one unexpired session record.
     *
     * @param username username represented by the containing file
     * @param line tab-separated session identifier and expiration timestamp
     * @return parsed identifier and session, or `null` for malformed or expired data
     */
    private fun parseRecord(username: String, line: String): Pair<String, StoredSession>? {
        val fields = line.split(RECORD_SEPARATOR, limit = 2)
        if (fields.size != 2 || !SESSION_ID_PATTERN.matches(fields[0])) return null

        val expiresAt = fields[1].toLongOrNull() ?: return null
        if (expiresAt <= currentEpochSeconds()) return null

        return fields[0] to StoredSession(username, expiresAt)
    }

    /**
     * Rewrites or removes one user's session file to match current in-memory state.
     *
     * @param username user whose active sessions should be persisted
     * @throws java.io.IOException when session data cannot be written or moved
     */
    private fun persistUser(username: String) {
        val records = sessions.entries
            .filter { it.value.username == username }
            .sortedBy { it.key }
        val destination = sessionFile(username)

        if (records.isEmpty()) {
            Files.deleteIfExists(destination.toPath())
            return
        }

        replaceFile(destination, records.joinToString("\n", postfix = "\n") {
            "${it.key}$RECORD_SEPARATOR${it.value.expiresAt}"
        })
    }

    /**
     * Atomically replaces a session file when the filesystem supports it.
     *
     * @param destination final session file
     * @param content complete plaintext file contents
     * @throws java.io.IOException when the temporary or destination file cannot be written
     */
    private fun replaceFile(destination: File, content: String) {
        val temporary = File(directory, ".${destination.name}.${UUID.randomUUID()}.tmp")
        temporary.writeText(content)
        restrictPermissions(temporary)

        try {
            Files.move(temporary.toPath(), destination.toPath(), REPLACE_EXISTING, ATOMIC_MOVE)
        } catch (_: AtomicMoveNotSupportedException) {
            Files.move(temporary.toPath(), destination.toPath(), REPLACE_EXISTING)
        }

        restrictPermissions(destination)
    }

    /**
     * Limits a session file to owner read and write access where supported.
     *
     * @param file session file whose permissions should be restricted
     */
    private fun restrictPermissions(file: File) {
        file.setReadable(false, false)
        file.setWritable(false, false)
        file.setExecutable(false, false)
        file.setReadable(true, true)
        file.setWritable(true, true)
    }

    /**
     * Validates the identifier and username before persisting a session.
     *
     * @param id opaque session identifier generated by Ktor
     * @param username authenticated username to store
     * @throws IllegalArgumentException when either value is invalid
     */
    private fun requireValidSession(id: String, username: String) {
        require(SESSION_ID_PATTERN.matches(id)) { "Invalid session identifier" }
        require(UserManager.isValidUsername(username)) { "Invalid session username" }
    }

    /**
     * Calculates the expiration timestamp for a newly stored session.
     *
     * @return expiration time as Unix epoch seconds
     * @throws ArithmeticException when the configured lifetime overflows a timestamp
     */
    private fun expirationTime(): Long {
        return Math.addExact(currentEpochSeconds(), lifetimeSeconds)
    }

    /**
     * Creates the file path assigned to a validated username.
     *
     * @param username username represented by the session file
     * @return session file inside the configured directory
     */
    private fun sessionFile(username: String): File {
        return File(directory, "$username$SESSION_FILE_SUFFIX")
    }

    /**
     * Creates Ktor's expected exception for an unavailable session identifier.
     *
     * @param id unavailable session identifier
     * @return missing-session exception
     */
    private fun missingSession(id: String): NoSuchElementException {
        return NoSuchElementException("Session not found: $id")
    }
}

/**
 * Associates an authenticated username with a server-side expiration timestamp.
 *
 * @param username authenticated account name
 * @param expiresAt expiration time as Unix epoch seconds
 */
private data class StoredSession(
    val username: String,
    val expiresAt: Long
)
