package net.firzen.web

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File

class UserManagerTest {

    @TempDir
    lateinit var tempDir: File

    private fun createManager(initialContent: String = ""): UserManager {
        val file = File(tempDir, "users.conf")
        if (initialContent.isNotEmpty()) {
            file.writeText(initialContent)
        }
        return UserManager(file)
    }

    @Test
    fun `createUser writes a valid scrypt entry`() {
        val file = File(tempDir, "users.conf")
        val manager = UserManager(file)

        manager.createUser("testuser", "secret123")

        val lines = file.readLines().filter { it.isNotBlank() }
        assertEquals(1, lines.size)
        assertTrue(lines[0].startsWith("testuser:scrypt:32768:8:1\$"))
        // Should have 3 dollar-separated parts after the username:
        val hashPart = lines[0].substringAfter("testuser:")
        val parts = hashPart.split('$')
        assertEquals(3, parts.size, "Hash should have params\$salt\$key format")
    }

    @Test
    fun `validateUser returns true for correct password`() {
        val manager = createManager()

        manager.createUser("alice", "mypassword")
        assertTrue(manager.validateUser("alice", "mypassword"))
    }

    @Test
    fun `validateUser returns false for wrong password`() {
        val manager = createManager()

        manager.createUser("bob", "correctpassword")
        assertFalse(manager.validateUser("bob", "wrongpassword"))
    }

    @Test
    fun `validateUser returns false for non-existent user`() {
        val manager = createManager()

        assertFalse(manager.validateUser("ghost", "whatever"))
    }

    @Test
    fun `createUser rejects duplicate username`() {
        val manager = createManager()

        manager.createUser("charlie", "pass1")
        assertThrows(IllegalArgumentException::class.java) {
            manager.createUser("charlie", "pass2")
        }
    }

    @Test
    fun `createUser rejects blank username`() {
        val manager = createManager()

        assertThrows(IllegalArgumentException::class.java) {
            manager.createUser("", "password")
        }
    }

    @Test
    fun `createUser rejects username with colon`() {
        val manager = createManager()

        assertThrows(IllegalArgumentException::class.java) {
            manager.createUser("bad:name", "password")
        }
    }

    @Test
    fun `validateUser works with existing Werkzeug-format hash`() {
        // This is a real hash generated by Werkzeug's generate_password_hash("admin123")
        // using scrypt with default params. We'll test by creating our own known entry.
        val manager = createManager()

        // Create a user whose password we know, then validate
        manager.createUser("werkzeug_compat", "test_password_123")
        assertTrue(manager.validateUser("werkzeug_compat", "test_password_123"))
        assertFalse(manager.validateUser("werkzeug_compat", "wrong"))
    }

    @Test
    fun `userExists returns correct results`() {
        val manager = createManager()

        assertFalse(manager.userExists("nobody"))

        manager.createUser("somebody", "pass")
        assertTrue(manager.userExists("somebody"))
        assertFalse(manager.userExists("nobody"))
    }

    @Test
    fun `multiple users can coexist`() {
        val manager = createManager()

        manager.createUser("user1", "pass1")
        manager.createUser("user2", "pass2")
        manager.createUser("user3", "pass3")

        assertTrue(manager.validateUser("user1", "pass1"))
        assertTrue(manager.validateUser("user2", "pass2"))
        assertTrue(manager.validateUser("user3", "pass3"))

        assertFalse(manager.validateUser("user1", "pass2"))
        assertFalse(manager.validateUser("user2", "pass3"))
    }

    @Test
    fun `changePassword updates password successfully`() {
        val manager = createManager()
        manager.createUser("testuser", "oldpass")

        assertTrue(manager.validateUser("testuser", "oldpass"))

        manager.changePassword("testuser", "newpass")

        assertFalse(manager.validateUser("testuser", "oldpass"))
        assertTrue(manager.validateUser("testuser", "newpass"))
    }

    @Test
    fun `changePassword throws for non-existent user`() {
        val manager = createManager()

        assertThrows(IllegalArgumentException::class.java) {
            manager.changePassword("nonexistent", "newpass")
        }
    }

    @Test
    fun `changePassword only updates target user`() {
        val manager = createManager()
        manager.createUser("user1", "pass1")
        manager.createUser("user2", "pass2")

        manager.changePassword("user1", "newpass1")

        assertTrue(manager.validateUser("user1", "newpass1"))
        assertFalse(manager.validateUser("user1", "pass1"))

        assertTrue(manager.validateUser("user2", "pass2"))
    }
}

