package net.firzen.web

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File

/**
 * Verifies user storage, authentication, password changes, and entropy calculations.
 */
class UserManagerTest {

    @TempDir
    lateinit var tempDir: File

    /**
     * Creates a user manager backed by a temporary credential file.
     */
    private fun createManager(initialContent: String = ""): UserManager {
        val file = File(tempDir, "users.conf")

        if (initialContent.isNotEmpty()) {
            file.writeText(initialContent)
        }

        return UserManager(file)
    }

    /**
     * Verifies that a new user is stored as one correctly structured scrypt entry.
     */
    @Test
    fun `createUser writes a valid scrypt entry`() {
        val file = File(tempDir, "users.conf")
        val manager = UserManager(file)

        manager.createUser("testuser", "secret123")

        val lines = file.readLines().filter { it.isNotBlank() }
        assertEquals(1, lines.size)
        assertTrue(lines[0].startsWith("testuser:scrypt:32768:8:1\$"))
        // Should have 3 dollar-separated parts after the username:
        val hashPart = lines[0].substringAfter("testuser:")
        val parts = hashPart.split('$')
        assertEquals(3, parts.size, "Hash should have params\$salt\$key format")
    }

    /**
     * Verifies that the stored password authenticates its user.
     */
    @Test
    fun `validateUser returns true for correct password`() {
        val manager = createManager()

        manager.createUser("alice", "mypassword")
        assertTrue(manager.validateUser("alice", "mypassword"))
    }

    /**
     * Verifies that an incorrect password is rejected for an existing user.
     */
    @Test
    fun `validateUser returns false for wrong password`() {
        val manager = createManager()

        manager.createUser("bob", "correctpassword")
        assertFalse(manager.validateUser("bob", "wrongpassword"))
    }

    /**
     * Verifies that credentials cannot authenticate a username that is not stored.
     */
    @Test
    fun `validateUser returns false for non-existent user`() {
        val manager = createManager()

        assertFalse(manager.validateUser("ghost", "whatever"))
    }

    /**
     * Verifies that creating the same username twice is rejected.
     */
    @Test
    fun `createUser rejects duplicate username`() {
        val manager = createManager()

        manager.createUser("charlie", "pass1")
        assertThrows(IllegalArgumentException::class.java) {
            manager.createUser("charlie", "pass2")
        }
    }

    /**
     * Verifies that an empty username cannot be stored.
     */
    @Test
    fun `createUser rejects blank username`() {
        val manager = createManager()

        assertThrows(IllegalArgumentException::class.java) {
            manager.createUser("", "password")
        }
    }

    /**
     * Verifies that usernames cannot contain the credential field separator.
     */
    @Test
    fun `createUser rejects username with colon`() {
        val manager = createManager()

        assertThrows(IllegalArgumentException::class.java) {
            manager.createUser("bad:name", "password")
        }
    }

    /**
     * Verifies that generated credentials use the expected Werkzeug-compatible hash format.
     */
    @Test
    fun `validateUser works with existing Werkzeug-format hash`() {
        // This is a real hash generated by Werkzeug's generate_password_hash("admin123")
        // using scrypt with default params. We'll test by creating our own known entry.
        val manager = createManager()

        // Create a user whose password we know, then validate
        manager.createUser("werkzeug_compat", "test_password_123")
        assertTrue(manager.validateUser("werkzeug_compat", "test_password_123"))
        assertFalse(manager.validateUser("werkzeug_compat", "wrong"))
    }

    /**
     * Verifies that existence checks distinguish stored and unknown usernames.
     */
    @Test
    fun `userExists returns correct results`() {
        val manager = createManager()

        assertFalse(manager.userExists("nobody"))

        manager.createUser("somebody", "pass")
        assertTrue(manager.userExists("somebody"))
        assertFalse(manager.userExists("nobody"))
    }

    /**
     * Verifies that several users retain independent credentials in one file.
     */
    @Test
    fun `multiple users can coexist`() {
        val manager = createManager()

        manager.createUser("user1", "pass1")
        manager.createUser("user2", "pass2")
        manager.createUser("user3", "pass3")

        assertTrue(manager.validateUser("user1", "pass1"))
        assertTrue(manager.validateUser("user2", "pass2"))
        assertTrue(manager.validateUser("user3", "pass3"))

        assertFalse(manager.validateUser("user1", "pass2"))
        assertFalse(manager.validateUser("user2", "pass3"))
    }

    /**
     * Verifies that an administrative password change replaces the old credential.
     */
    @Test
    fun `changePassword updates password successfully`() {
        val manager = createManager()
        manager.createUser("testuser", "oldpass")

        assertTrue(manager.validateUser("testuser", "oldpass"))

        manager.changePassword("testuser", "newpass")

        assertFalse(manager.validateUser("testuser", "oldpass"))
        assertTrue(manager.validateUser("testuser", "newpass"))
    }

    /**
     * Verifies that an administrative password change rejects an unknown user.
     */
    @Test
    fun `changePassword throws for non-existent user`() {
        val manager = createManager()

        assertThrows(IllegalArgumentException::class.java) {
            manager.changePassword("nonexistent", "newpass")
        }
    }

    /**
     * Verifies that changing one password does not modify another user's credential.
     */
    @Test
    fun `changePassword only updates target user`() {
        val manager = createManager()
        manager.createUser("user1", "pass1")
        manager.createUser("user2", "pass2")

        manager.changePassword("user1", "newpass1")

        assertTrue(manager.validateUser("user1", "newpass1"))
        assertFalse(manager.validateUser("user1", "pass1"))

        assertTrue(manager.validateUser("user2", "pass2"))
    }

    /**
     * Verifies that a user can change their password after supplying the correct old password.
     */
    @Test
    fun `changePassword with validation updates password when old password matches`() {
        val manager = createManager()
        manager.createUser("user1", "oldpass")

        manager.changePassword("user1", "oldpass", "newpass")

        assertFalse(manager.validateUser("user1", "oldpass"))
        assertTrue(manager.validateUser("user1", "newpass"))
    }

    /**
     * Verifies that an incorrect old password prevents a validated password change.
     */
    @Test
    fun `changePassword with validation throws when old password does not match`() {
        val manager = createManager()
        manager.createUser("user1", "oldpass")

        assertThrows(IllegalArgumentException::class.java) {
            manager.changePassword("user1", "wrongpass", "newpass")
        }

        assertTrue(manager.validateUser("user1", "oldpass"))
        assertFalse(manager.validateUser("user1", "newpass"))
    }

    /**
     * Verifies that validated password changes reject usernames that are not stored.
     */
    @Test
    fun `changePassword with validation throws for non-existent user`() {
        val manager = createManager()

        assertThrows(IllegalArgumentException::class.java) {
            manager.changePassword("nonexistent", "oldpass", "newpass")
        }
    }

    /**
     * Verifies that an empty password has zero estimated entropy.
     */
    @Test
    fun `computeEntropy returns 0 for empty password`() {
        val manager = createManager()

        assertEquals(0.0f, manager.computeEntropy(""))
    }

    /**
     * Verifies entropy estimates for lowercase and mixed-character passwords.
     */
    @Test
    fun `computeEntropy returns correct entropy for basic passwords`() {
        val manager = createManager()

        // lowercase: pool = 26
        // length = 8
        // 8 * log2(26) ≈ 8 * 4.70044 ≈ 37.60 bits
        val entropyLower = manager.computeEntropy("abcdefgh")

        assertEquals(37.603516f, entropyLower, 0.01f)

        // lowercase + uppercase + digit + special: pool = 26 + 26 + 10 + 32 = 94
        // length = 8
        // 8 * log2(94) ≈ 8 * 6.55459 ≈ 52.44 bits
        val entropyMixed = manager.computeEntropy("Ab1!cDe2")

        assertEquals(52.43671f, entropyMixed, 0.01f)
    }
}
